version: '3'

services:
  php:
    image: php:fpm-alpine
    container_name: php
    expose:
      - 9000
    volumes:
      - ./:/var/www/

  nginx:
    build: .
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    links:
      - php
